export const transliteration_languages = [
  { code: "am", name: "Amharic" },
  { code: "ar", name: "Arabic" },
  { code: "bn", name: "Bangla" },
  { code: "be", name: "Belarusian" },
  { code: "bg", name: "Bulgarian" },
  { code: "yue-hant", name: "Chinese (Hong Kong)" },
  { code: "zh", name: "Chinese (Simplified)" },
  { code: "zh-hant", name: "Chinese (Traditional)" },
  { code: "fr", name: "French" },
  { code: "de", name: "German" },
  { code: "el", name: "Greek" },
  { code: "gu", name: "Gujarati" },
  { code: "he", name: "Hebrew" },
  { code: "hi", name: "Hindi" },
  { code: "it", name: "Italian" },
  { code: "ja", name: "Japanese" },
  { code: "kn", name: "Kannada" },
  { code: "ml", name: "Malayalam" },
  { code: "mr", name: "Marathi" },
  { code: "ne", name: "Nepali" },
  { code: "or", name: "Odia" },
  { code: "fa", name: "Persian" },
  { code: "pt", name: "Portuguese (Brazil)" },
  { code: "pa", name: "Punjabi" },
  { code: "ru", name: "Russian" },
  { code: "sa", name: "Sanskrit" },
  { code: "sr", name: "Serbian" },
  { code: "si", name: "Sinhala" },
  { code: "es", name: "Spanish" },
  { code: "ta", name: "Tamil" },
  { code: "te", name: "Telugu" },
  { code: "ti", name: "Tigrinya" },
  { code: "uk", name: "Ukrainian" },
  { code: "ur", name: "Urdu" },
  { code: "vi", name: "Vietnamese" },
];
